### PR TITLE
Localization for Brazilian Portuguese (pt-br)

### PR DESCRIPTION
**Pull request by Kahlis**
This pull request introduces a new locale file and option in locale menu for Brazilian Portuguese (pt-br). I took the liberty of not only translating but also localizing some expressions to make it more appealing to the Brazilian audience.

### Files Modified:
(new) client/src/locales/pt-br.ts
(updated) client/src/components/navbar/LocaleSelector.vue

Tested with some friends.

### CODE REVIEW

**Review by dyc3 — APPROVED** [review]

**Comment by dyc3** [comment]
Thanks! Just fix the formatting with `yarn format` and this will be good to merge

**Comment by Kahlis** [comment]
Sure, in my future contribuitions I'll remember to do that before PR. Thank you!

**Comment by Kahlis** [comment]
Yarn format is not a script in package-json, so I used `yarn lint` that probably is what you meant. Also make some casing corrections that I thought was necessary.

**Comment by dyc3** [comment]
Yup, thats what i meant.

**Pull request merged**
