### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by FriedrichGaming**
This pull request currently adds basic german translation. I'll probably add more translations in the next few days. If you want to merge this pull request already, i can open a new one for further translations.

partially fix for: #616

Also fixes this:
grafik

### CODE REVIEW

**Review by dyc3 — CHANGES_REQUESTED** [review]
Please exclude untranslated strings. It will automatically fall back to english.

Otherwise, I can't read German. Rubber stamp LGTM!

**Comment by FriedrichGaming** [comment]
Should I also remove references to other string that weren't changed?
Like for example:
grafik

**Comment by dyc3** [comment]
Yes, that would make sense.

**Comment by FriedrichGaming** [comment]
That should be it. It's currently 5:40am in germany so i'm gonna sleep now.

There are still some inconsistencies regarding the use of formal or informal language but i'll fix those in another pull request.

**Review by dyc3 — APPROVED** [review]
Run `yarn lint` to fix the linting errors

**Pull request merged**
