### PR TITLE
Error handling when getting room from database

### LINKED ISSUE #101: Unhandled rejection TypeError when attempting to find a room that no longer exists
```
[ws] CONNECTION ESTABLISHED  /api/room/c4cdd5aa-d89d-42cd-bdde-4f1de5415878 1
Grabbing room c4cdd5aa-d89d-42cd-bdde-4f1de5415878 from db
Executing (default): SELECT "id", "name", "title", "description", "createdAt", "updatedAt" FROM "Rooms" AS "Room" WHERE "Room"."name" = 'c4cdd5aa-d89d-42cd-bdde-4f1de5415878' LIMIT 1;
Unhandled rejection TypeError: Cannot convert undefined or null to object
    at Room.findOne.then.room (/home/carson/opentogethertube/storage.js:8:4)
    at tryCatcher (/home/carson/opentogethertube/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/carson/opentogethertube/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/carson/opentogethertube/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

### PR DESCRIPTION
**Pull request by adapap**
When a room is not found, this throws an error because room is undefined.

fixes #101

### CODE REVIEW

**Comment by adapap** [comment]
I think the websocket implementation needs a bit of a rework. It's not very prone to any error handling with all of the promises assuming that rooms are defined, videos are available, users are in the lobby, etc. This PR now fixes existing errors but only in the most basic sense.

**Comment by dyc3** [comment]
However, I can verify that this does fix #101

**Comment by adapap** [comment]
```js
getRoom(roomName).then(result => {
    if (!result) {
        console.error("[ws] Room doesn't exist");
        ws.close(4002, "Room doesn't exist");
        return;
    }
    rooms[roomName].clients.push({
        name: "client",
        socket: ws,
    });
    console.log("[ws] client joined", roomName);
}).then(() => {
    ws.on('message', (message) => {
        console.log('[ws] received:', typeof(message), message);
```
I don't think I understand this piece of code. Why is there a second `.then()`? The first promise should be rejected with the return? It looks like the returns here and on line 217:
```js
if (!msg.name) {
    console.warn("name not supplied");
    return;
}
```
This probably needs a refactor to not use chained promises or handle rejections (I'm not that well versed in this).

**Comment by dyc3** [comment]
I don't remember why I wrote it like that. I think it was so that I could just reuse the code I had from before and not have to change anything. Tell you what: I'll rework that bit in a separate branch. I wanna get this one merged in.

**Pull request merged**
