### PR TITLE
Chat rework

### LINKED ISSUE #622: Chat in Fullscreen Mode
### Is your feature request related to a problem? Please describe.

OpenTogetherTube is almost the perfect replacement for Metastream.
Unfortunately there's no way to use or see the chat in full-screen mode for the best experience.

### Describe the solution you'd like

I would like to use the chat function in full-screen video mode like it's happening in Metastream with an overlay box you make appear by pressing Enter on the keyboard. Would it be possible to implement that feature?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dyc3**
- refactor(Chat): use composition api instead
- move Chat inside video player
- adds hotkey <kbd>t</kbd> to open char, and close it with <kbd>Esc</kbd> while text box is focused.

Closes #622

### CODE REVIEW

**Comment by dyc3** [comment]
I've canaried some changes to the chat UI to https://opentogether-chat-rewor-7vf9tf.herokuapp.com/ Looking for feedback. Let me know what you think

**Comment by Shu2ik** [comment]
It would work out as basic idea.
The time the comments stay on screen is good 👍

These things could be optimized
• It's rather small the way it looks, especially in width. Makes it difficult to overview if needed. I think you can double the size and make the window slightly transparent maybe
• More padding could be added to the notification boxes especially on left side
• Sometimes comments get cut off if you post up to 5 or keep posting
• Activation and navigation without mouse is still missing I assume

This is the first impression so far.

**Comment by Shu2ik** [comment]
So putting the text field into the player bar is not within the bound of possibility?

**Comment by dyc3** [comment]
Yeah, looks are not final. Will definitely make the chat and font size bigger, but I need to handle smaller screens more gracefully first. You can activate the chat box with <kbd>t</kbd>, and close it with <kbd>Esc</kbd>. (Should've mentioned that)

> So putting the text field into the player bar is not within the bound of possibility?

I mean it's technically possible, but I'm not going to, mostly because it would dramatically increase complexity.

**Comment by Shu2ik** [comment]
Alright. Guessed so that it's a mock-up more or less.
Overall it's fine, just needs a balanced size ratio between different screens indeed.

Btw, in fullscreen Esc is closing the mode instead of closing the chat.
I expected having the chat box key on 'c' and didn't try 't' which is supposed to stand for text I guess.

**Comment by dyc3** [comment]
Unfortunately, I found out that its not possible to override escape exiting fullscreen. As an alternative, <kbd>Enter</kbd> with no message in the chat box will close the chat without sending a message. I've made all of the other changes though.

I think the last thing I want to change is the location of the user list, but I think I will leave that for another PR.

**Comment by dyc3** [comment]
If there's no remaining feedback, I'm going to merge this in by the end of the day.

**Comment by Shu2ik** [comment]
Looking good and working smoothly. That will do 👍
Opening chat with Enter isn't possible? For consistency.

**Comment by dyc3** [comment]
I think opening chat with Enter has the potential to cause ambiguity and confusion from blind users. Enter usually means "Confirm" or "Send" or "Do this" or "Click". So from an accessibility standpoint, no I don't think its possible.

**Comment by Shu2ik** [comment]
I see. It's a minor detail, no worries.
Thank you for the rework.

**Comment by Shu2ik** [comment]
Will the changes only appear on that specific page or are you going to apply it to the main page as well?
https://opentogether-chat-rewor-7vf9tf.herokuapp.com/

**Comment by dyc3** [comment]
It should have deployed by now, i'll do a manual deploy right now

**Pull request merged**
